language: node_js
node_js:
- node
before_install:
  -openssl aes-256-cbc -K $encrypted_cc022ba7de21_key -iv $encrypted_cc022ba7de21_iv
  -in deploy_rsa.enc -out $TRAVIS_BUILD_DIR/deploy_rsa -d
addons:
  ssh_known_hosts: 45.32.234.128
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
  - ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
  - npm run deploy
